name: Publish babel-plugin-jsx-panorama-expressions
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm --frozen-lockfile
      - run: pnpm build:jsx
      - run: pnpm publish dist/babel-plugin-jsx-panorama-expressions --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}