name: Publish panorama-all-in-jsx
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm --frozen-lockfile
      - run: pnpm build:macros
      - run: cp packages/panorama-all-in-jsx/README.md dist/panorama-all-in-jsx/
      - run: pnpm publish dist/panorama-all-in-jsx --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}