name: Publish solid-panorama-polyfill
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm --frozen-lockfile
      - run: pnpm build:polyfill
      - run: cp packages/panorama-polyfill/README.md dist/solid-panorama-polyfill/
      - run: pnpm publish dist/solid-panorama-polyfill --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}